//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARQUIVOS
    {
        public System.DateTime data_carga { get; set; }
        public string codigo_camera { get; set; }
        public string numero_veiculo { get; set; }
        public string arquivo { get; set; }
        public string sigla_equipe { get; set; }
    }
}
