//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMERAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAMERAS()
        {
            this.HISTORICOS_CAMERAS = new HashSet<HISTORICOS_CAMERAS>();
        }
    
        public string codigo_camera { get; set; }
        public string bpm_camera { get; set; }
        public string codigo_barra_camera { get; set; }
        public int ativo { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> DATA_BAIXA { get; set; }
        public string MOTIVO_BAIXA { get; set; }
        public string USUARIO_BAIXA { get; set; }
        public Nullable<System.DateTime> DATA_AQUISICAO { get; set; }
        public Nullable<int> CODIGO_EMPRESA { get; set; }
        public string PRONTUARIO { get; set; }
    
        public virtual EMPRESAS EMPRESAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORICOS_CAMERAS> HISTORICOS_CAMERAS { get; set; }
    }
}
