//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCARGAS
    {
        public int CODIGO_DESCARGA { get; set; }
        public System.DateTime DATA_DESCARGA { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public string NUMERO_HD { get; set; }
    }
}
