//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elektroEntities : DbContext
    {
        public elektroEntities()
            : base("name=elektroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ATIVIDADES> ATIVIDADES { get; set; }
        public virtual DbSet<DESCARGAS> DESCARGAS { get; set; }
        public virtual DbSet<FUNCIONARIOS> FUNCIONARIOS { get; set; }
        public virtual DbSet<GERENCIA> GERENCIA { get; set; }
        public virtual DbSet<HD> HD { get; set; }
        public virtual DbSet<LOCALIDADE> LOCALIDADE { get; set; }
        public virtual DbSet<MOVIMENTACAO_CAMERA> MOVIMENTACAO_CAMERA { get; set; }
        public virtual DbSet<NAO_CONFORMIDADES> NAO_CONFORMIDADES { get; set; }
        public virtual DbSet<PERMISSOES_USUARIO> PERMISSOES_USUARIO { get; set; }
        public virtual DbSet<RECONHECIMENTOS_POSITIVOS> RECONHECIMENTOS_POSITIVOS { get; set; }
        public virtual DbSet<REGIAO> REGIAO { get; set; }
        public virtual DbSet<SUPERVISAO> SUPERVISAO { get; set; }
        public virtual DbSet<TIPOS_OCORRENCIAS> TIPOS_OCORRENCIAS { get; set; }
        public virtual DbSet<TIPOS_TRABALHOS> TIPOS_TRABALHOS { get; set; }
        public virtual DbSet<ARQUIVOS> ARQUIVOS { get; set; }
        public virtual DbSet<OCORRENCIAS> OCORRENCIAS { get; set; }
        public virtual DbSet<TIPOS_USUARIOS> TIPOS_USUARIOS { get; set; }
        public virtual DbSet<USUARIOS> USUARIOS { get; set; }
        public virtual DbSet<EMPRESAS> EMPRESAS { get; set; }
        public virtual DbSet<HISTORICO_VEICULO> HISTORICO_VEICULO { get; set; }
        public virtual DbSet<TIPOS_VEICULOS> TIPOS_VEICULOS { get; set; }
        public virtual DbSet<VEICULOS> VEICULOS { get; set; }
        public virtual DbSet<ESCALA_COD> ESCALA_COD { get; set; }
        public virtual DbSet<MOVIMENTACAO_HD> MOVIMENTACAO_HD { get; set; }
        public virtual DbSet<FALHAS_EVENTOS_PROCESSOS> FALHAS_EVENTOS_PROCESSOS { get; set; }
        public virtual DbSet<EQUIPES> EQUIPES { get; set; }
        public virtual DbSet<SORTEIOS> SORTEIOS { get; set; }
        public virtual DbSet<VIDEOS> VIDEOS { get; set; }
        public virtual DbSet<REGISTRO_OCORRENCIAS> REGISTRO_OCORRENCIAS { get; set; }
        public virtual DbSet<SORTEADOS> SORTEADOS { get; set; }
        public virtual DbSet<LISTA_VIDEOS> LISTA_VIDEOS { get; set; }
        public virtual DbSet<CAMERAS> CAMERAS { get; set; }
        public virtual DbSet<HISTORICOS_CAMERAS> HISTORICOS_CAMERAS { get; set; }
    }
}
