//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FUNCIONARIOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public string prontuario { get; set; }
        public string nome_funcionario { get; set; }
        public string funcao { get; set; }
        public Nullable<int> localidade { get; set; }
        public Nullable<int> supervisao { get; set; }
        public Nullable<int> gerencia { get; set; }
        public Nullable<int> regiao { get; set; }
        public string prontuario_gestor { get; set; }
        public string nome_gestor { get; set; }
        public string periodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
