//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HD()
        {
            this.MOVIMENTACAO_HD = new HashSet<MOVIMENTACAO_HD>();
        }
    
        public string NUMERO_HD { get; set; }
        public string NUMERO_SERIE { get; set; }
        public string STATUS { get; set; }
        public Nullable<int> LOCAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTACAO_HD> MOVIMENTACAO_HD { get; set; }
    }
}
