//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICOS_CAMERAS
    {
        public int COD_HISTORICO { get; set; }
        public string SIGLA_EQUIPE { get; set; }
        public string CODIGO_CAMERA { get; set; }
        public int TIPO { get; set; }
        public Nullable<int> EMPRESA_MANUTENCAO { get; set; }
        public string OBSERVACAO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> DATA_REGISTRO { get; set; }
        public Nullable<System.DateTime> DATA_ALOCACAO { get; set; }
        public Nullable<System.DateTime> DATA_DESALOCAO { get; set; }
        public Nullable<System.DateTime> DATA_ENVIO { get; set; }
        public Nullable<System.DateTime> DATA_RECEBIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_BAIXA { get; set; }
        public string NUMERO_RASTREIO { get; set; }
        public string PRONTUARIO { get; set; }
    
        public virtual CAMERAS CAMERAS { get; set; }
        public virtual EQUIPES EQUIPES { get; set; }
    }
}
