//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_VEICULO
    {
        public int NUMERO_HISTORICO { get; set; }
        public string PLACA_VEICULO { get; set; }
        public string SIGLA_EQUIPE { get; set; }
        public string OBSERVACAO_VINCULAR { get; set; }
        public string OBSERVACAO_DESVINCULAR { get; set; }
        public string USUARIO_VINCULAR { get; set; }
        public string USUARIO_DESVINCULAR { get; set; }
        public Nullable<System.DateTime> DATA_VINCULAR { get; set; }
        public Nullable<System.DateTime> DATA_DESVINCULAR { get; set; }
    
        public virtual EQUIPES EQUIPES { get; set; }
    }
}
