//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCALIDADE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOCALIDADE()
        {
            this.MOVIMENTACAO_HD = new HashSet<MOVIMENTACAO_HD>();
            this.MOVIMENTACAO_HD1 = new HashSet<MOVIMENTACAO_HD>();
            this.EQUIPES = new HashSet<EQUIPES>();
        }
    
        public int CODIGO_LOCALIDADE { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<int> CODIGO_SUPERVISAO { get; set; }
    
        public virtual SUPERVISAO SUPERVISAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTACAO_HD> MOVIMENTACAO_HD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOVIMENTACAO_HD> MOVIMENTACAO_HD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQUIPES> EQUIPES { get; set; }
    }
}
