//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMENTACAO_CAMERA
    {
        public int NUMERO_MOVIMENTACAO { get; set; }
        public string SIGLA_EQUIPE { get; set; }
        public string CODIGO_CAMERA { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> EMPRESA_MANUTENCAO { get; set; }
        public string OBSERVACAO { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> DATA_REGISTRO { get; set; }
        public Nullable<System.DateTime> DATA_INICIO { get; set; }
        public Nullable<System.DateTime> DATA_FIM { get; set; }
        public string NUMERO_RASTREIO { get; set; }
        public string OBSERVACAO_DESVINCULAR { get; set; }
    
        public virtual EQUIPES EQUIPES { get; set; }
    }
}
