//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMENTACAO_HD
    {
        public int NUMERO_MOVIMENTACAO { get; set; }
        public string NUMERO_HD { get; set; }
        public Nullable<System.DateTime> DATA_CHEGADA { get; set; }
        public string RESPONSAVEL { get; set; }
        public Nullable<int> LOCAL_REGISTRO { get; set; }
        public Nullable<int> LOCAL_DESTINO { get; set; }
        public string OBSERVACAO { get; set; }
        public string NUMERO_PROTOCOLO { get; set; }
        public Nullable<System.DateTime> DATA_REGISTRO { get; set; }
        public string TIPO { get; set; }
        public string MONITORIA { get; set; }
        public string USUARIO_REGISTRO { get; set; }
        public string USUARIO_REGISTRO_RECEBIMENTO { get; set; }
        public Nullable<System.DateTime> DATA_ENVIO { get; set; }
        public Nullable<System.DateTime> DATA_PROVAVEL_RECEBIMENTO { get; set; }
    
        public virtual HD HD { get; set; }
        public virtual LOCALIDADE LOCALIDADE { get; set; }
        public virtual LOCALIDADE LOCALIDADE1 { get; set; }
    }
}
