//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAO_CONFORMIDADES
    {
        public int id_nao_conformidade { get; set; }
        public string tipo { get; set; }
        public string atividade { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public int severidade { get; set; }
    }
}
