//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSOES_USUARIO
    {
        public int ID_PERMISSAO { get; set; }
        public int ID_TIPO_USUARIO { get; set; }
        public int ID_MENU { get; set; }
        public int ID_SUBMENU { get; set; }
    }
}
