//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECONHECIMENTOS_POSITIVOS
    {
        public int id_rec_positivo { get; set; }
        public string tipo { get; set; }
        public string atividade { get; set; }
        public string descricao_rec_positivo { get; set; }
    }
}
