//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_OCORRENCIAS
    {
        public int CODIGO_REGISTRO_OCORRENCIA { get; set; }
        public Nullable<int> CODIGO_TIPO_OCORRENCIA { get; set; }
        public Nullable<int> CODIGO_ATIVIDADE { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<int> CODIGO_VALIDACAO { get; set; }
        public string USUARIO_VALIDACAO { get; set; }
        public Nullable<System.DateTime> DATA_VALIDACAO { get; set; }
        public string OBSERVACAO_VALIDACAO { get; set; }
        public Nullable<int> CODIGO_SEVERIDADE { get; set; }
        public string NUMERO_HD { get; set; }
        public Nullable<int> COD_SORTEADOS { get; set; }
        public Nullable<int> COD_LISTA_VIDEOS { get; set; }
        public string SIGLA_EQUIPE { get; set; }
        public Nullable<System.DateTime> DATA_INICIAL { get; set; }
        public Nullable<System.DateTime> DATA_FINAL { get; set; }
        public string tipo_ocorrencia { get; set; }
        public Nullable<int> COD_FALHA_EVENTO { get; set; }
    
        public virtual ATIVIDADES ATIVIDADES { get; set; }
        public virtual EQUIPES EQUIPES { get; set; }
        public virtual SORTEADOS SORTEADOS { get; set; }
        public virtual TIPOS_OCORRENCIAS TIPOS_OCORRENCIAS { get; set; }
        public virtual LISTA_VIDEOS LISTA_VIDEOS { get; set; }
        public virtual FALHAS_EVENTOS_PROCESSOS FALHAS_EVENTOS_PROCESSOS { get; set; }
    }
}
