//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public string prontuario_usuario { get; set; }
        public string nome_usuario { get; set; }
        public string senha_usuario { get; set; }
        public string email_usuario { get; set; }
        public int id_tipo_usuario { get; set; }
        public int ativo { get; set; }
        public string PRONTUARIO { get; set; }
    
        public virtual FUNCIONARIOS FUNCIONARIOS { get; set; }
        public virtual TIPOS_USUARIOS TIPOS_USUARIOS { get; set; }
    }
}
