//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamadaDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULOS
    {
        public string PLACA { get; set; }
        public string NUMERO { get; set; }
        public int COD_TIPO { get; set; }
        public int ativo { get; set; }
        public string SIGLA_EQUIPE { get; set; }
        public string observacao { get; set; }
    
        public virtual TIPOS_VEICULOS TIPOS_VEICULOS { get; set; }
    }
}
